### ISSUE TITLE
Conflict with torch serialzation

### ISSUE THREAD

**Issue by ffmpbgrnn** [deepmind/torch-hdf5#37]
Hi! `hdf5.HDF5File` is a torch class, and when do [serialization](https://github.com/torch/torch7/blob/master/doc/file.md#serialization-methods) the `read` and `write` function will be called which is now conflict with `hdf5.HDF5File`'s API.

**Comment by d11** [comment]
Ah yeah, that is a bit unfortunate. However, I probably won't change it for now because:
a) I don't want to change the API and break backwards compatibility at this point.
b) A hdf5.HDF5File should not be serialized anyway. It is like a file handle, and should only be considered valid for the life of the program. If you want to serialize all the data in the file, you need to do that explicitly.
