### ISSUE TITLE
Loading HDF5 is Slow

### ISSUE THREAD

**Issue by adamist521** [deepmind/torch-hdf5#41]
I'm using hdf5 format file for transferring data between python and torch on ubuntu 14.04.
Somehow just opening big size (2GB~) hdf5 takes ages on `th` environment. 
(not loading any data on memory, just `f = hdf5.open('file.h5', 'r')` )

Is this only case for me? Any suggestions?

**Comment by d11** [comment]
Hmm, haven't encountered this, although I've mainly been using hdf5 for smaller datasets.
What kind of structure does the file have? It does query the contents to find out what paths are available when you open it, if I remember correctly. There are also some compression options you could try, although that might not help if the problem is occurring before even trying to load the data.

**Comment by adamist521** [comment]
Maybe having to many contents could be the reason. I have more than 30,000 data hanging...
I don't know about the other languages implementation but is it normal to query all the path at first?

I'll try compressing. Thanks.

This wouldn't probably the correct place to ask about HDF5 itself but doesn't it support large data?
How big would be the maximum size of data that HDF5 could handle with out a problem?

**Comment by Amir-Arsalan** [comment]
@adamist521 I know it's been a while, but did you figure out what the issue was eventually?
I think I'm facing the same issue:

https://github.com/deepmind/torch-hdf5/issues/112
