### ISSUE TITLE
Unable to write table to hdf5 file

### ISSUE THREAD

**Issue by coodoo** [deepmind/torch-hdf5#56]
Any idea on why simple test case like below will fail? Thanks.

```lua
questions = {{22,33}, {44,55}}
h5 = hdf5.open( 'train_data.h5', 'w')
h5:write('/trainset', questions )
h5:close()
```

**Comment by d11** [comment]
Two problems:
1) it expects data as Torch tensors rather than plain Lua numbers.
2) tables must be indexed by strings rather than numbers

For example you could do this instead:

local hdf5 = require 'hdf5'
questions = {a = torch.Tensor{22, 33}, b = torch.Tensor{44, 55}}
h5 = hdf5.open( 'train_data.h5', 'w')
h5:write('/trainset', questions )
h5:close()

**Comment by coodoo** [comment]
Thanks, about #2, is string keys a hard requirement from `hdf5` spec or only in this implementation? I didn't recall seeing that while using python.

In my case I have a rather large lua table storing 100,000+ tensors in the shape of `[100000x170]`, would really love to write that table out to hdf5 file without converting number index to strings first, any suggestion? 

For now I'm dumping it to disk with `t7`.

**Comment by d11** [comment]
That's just how this implementation works at the moment. There are lots of features from the hdf5 spec that are not included.

I'm not sure about the best option in your case - you could loop through the table and write it out a bit at a time, converting the keys as you go. But I would be tempted to write it as a single dataset (i.e. one tensor) since some users have reported performance degradation with large numbers of keys.

Bear in mind also that this library has not really been used much for large datasets - mainly just for transferring bits and pieces of data between Lua and other languages.

Cheers.

**Comment by coodoo** [comment]
Makes sense, I ended up using `nn.JoinTable(1)` to convert table to tensor before writing out the data, which worked fine thus far, thanks for the reminder though!
